name = "zapstore"
main = ".output/server/index.mjs"
compatibility_date = "2024-09-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"

# Em caso de deploy de Cloudflare Pages direto com build SPA:
# pages_build_output_dir = ".output/public"
